# Generated by Django 4.1.7 on 2023-04-14 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afro_dtl', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='gender',
            new_name='gendar',
        ),
    ]
