# Generated by Django 4.1.7 on 2023-04-14 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afro_dtl', '0002_rename_gender_useraccount_gendar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='gendar',
            new_name='gender',
        ),
    ]
